### ISSUE TITLE
Error: cannot find module 'babel-polyfill'

### ISSUE THREAD

**Issue by PeterCervienka** [relekang/lint-filter#31]
Hi,

I am getting following error, when I run lint

```
Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Itera\Projects\Cicero\hb-advisory\frontend\node_modules\lint-filter\lint-filter.js:2:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed.
    at Socket._writeGeneric (net.js:640:19)
    at Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Socket.Writable.write (_stream_writable.js:207:11)
    at Socket.write (net.js:618:40)
    at Console.log (console.js:36:16)
    at process.<anonymous> (C:\Itera\Projects\Cicero\hb-advisory\frontend\node_modules\eslint\bin\eslint.js:48:17)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
ERROR: lint:js:strict: None-Zero Exit(1);
```

One solution is install it manually via npm install babel-polyfill.

**Comment by relekang** [comment]
Thanks for reporting, this will be fixed in the next release.
